### PR TITLE
Hw1 branch pull request

### PR DESCRIPTION
**Pull request by turrilld**
### Code Changes I made:
1.  Completed Flexbox Froggy game and added answers.
2. Completed Palindrome exercise.  The palindrome checking and show/hide logic is in the javascript file, while the color and styling are in the HTML using bootstrap classes.  

### Why I made those changes
For the palindrome exercise I decided not to use a CSS page, and thus I tried to keep the functional and UI code separate.  Thus all the styling is in the HTML code, and the only code in the JS that effects the display is the hide/show code for the success, fail, and error messages.  

### What feedback I am looking for
For the palindrome exercise, anything related to other ways to structure the code for a better split between front and back end, better performance, or better appearance would be appreciated. For the froggy game, if you have an answer that uses fewer commands or different commands I would like to see it.

### CODE REVIEW

**Comment by emmayakley** [comment]
Hi Daniel! 

Your program looks good to me. I'm not sure if I have many suggestions but I did have a few questions, so I would suggest adding a few comments. 
The questions I had were why the isPalindrome function is defined twice (this might just be my misunderstanding of JavaScript, but may be helpful to have a comment for people who are less familiar). The other thing I had a question about isn't really a suggestion, but I was wondering where you formatted your text to be red/green for answering if the number was a palindrome.

 I also thought they way you handled outputting the different messages was a cool way to do it! If you didn't want to use .hidden, you could always use getElementById and innerText instead. An example would be:
`const outputDiv = document.getElementById("yes"); `
`outputDiv.innerText = "Yes. This is a palindrome!"`

Overall it looks good to me, great job!!

**Comment by turrilld** [comment]
> Hi Daniel!
> 
> Your program looks good to me. I'm not sure if I have many suggestions but I did have a few questions, so I would suggest adding a few comments. The questions I had were why the isPalindrome function is defined twice (this might just be my misunderstanding of JavaScript, but may be helpful to have a comment for people who are less familiar). The other thing I had a question about isn't really a suggestion, but I was wondering where you formatted your text to be red/green for answering if the number was a palindrome.
> 
> I also thought they way you handled outputting the different messages was a cool way to do it! If you didn't want to use .hidden, you could always use getElementById and innerText instead. An example would be: `const outputDiv = document.getElementById("yes"); ` `outputDiv.innerText = "Yes. This is a palindrome!"`
> 
> Overall it looks good to me, great job!!

Thanks for the review!  Good catch on the double definition, its code I forgot to clean up.  Ill have that updated shortly!

I implemented it the way I did to minimize the amount of CSS manipulation being done by the javascript.  I have no idea of this is the "right" way to implement it, and I think the innerText method is completely viable as well.  I didnt see anything in the style guide about it, so I will let it be for now!

**Comment by datdinh7719** [comment]
Hi Daniel,
I notice that when we first enter the program, it already display the "Yes. This is a palindrome!" message. It also display that message when we enter an invalid value such as "9-999282". I have attached screenshot of the issue below:
Screenshot 2024-10-20 at 5 07 26 PM
Screenshot 2024-10-20 at 5 07 38 PM

**Comment by mukundsai79** [comment]
Great job keeping the styling in HTML and focusing JavaScript on functionality, it keeps your code clean. Consider simplifying the palindrome check by comparing characters directly and using more descriptive variable names for better readability.

**Comment by turrilld** [comment]
> Hi Daniel, I notice that when we first enter the program, it already display the "Yes. This is a palindrome!" message. It also display that message when we enter an invalid value such as "9-999282". I have attached screenshot of the issue below: Screenshot 2024-10-20 at 5 07 26 PM Screenshot 2024-10-20 at 5 07 38 PM

Good catch.  I have fixed the issue (turns out numbers is a terrible input type) and it should now work as intended.

**Comment by turrilld** [comment]
> Great job keeping the styling in HTML and focusing JavaScript on functionality, it keeps your code clean. Consider simplifying the palindrome check by comparing characters directly and using more descriptive variable names for better readability.

Updated and compressed!

**Pull request merged**
