### PR TITLE
Pull Request for HW3

### PR DESCRIPTION
**Pull request by turrilld**
**Code Changes I made:**
Created a homepage with a view of south America from space.  Added a nav bar, a page that lists all the countries with their flags and a breif description.  A page with a graph for population, and another page with a graph for GDP.

**Why I made those changes:**
I was going for a more dark mode, space themed setup.  Hence the black background on two of my four pages.  Unfortunately, I was not able to change the color of the text or hashing on the graphs, so I left the graph pages white for readability.

**What feedback I am looking for:**
I have spotted a few issues that I was not able to resolve, such as not being able to change the text color of the graphs.  Any ideas on how to do that would be appriciated.  I was also not able to open StackBlitz's preview in its own window nor get the code to run locally yet, so I likely have unresolved accessibility issues that I was simply unable to see yet.  Beyond that any bugs or code improvement suggestions are always valuable.

### CODE REVIEW

**Comment by satvika-psu** [comment]
Hi Daniel, styling of your application looks very good ..... especially how the list view changes based on the size of the screen. I don't see any other bugs and ........you can open the stack blitz project in a browser window by clicking on the icon with the arrow pointing outwards located on the top right of the preview pan in your stack blitz ide.

**Comment by emmayakley** [comment]
Hi Daniel! As mentioned during class, I think you did a great job styling your application! I would add an alternate tag for your flag image if it's not provided, since the API has a text description of the flags as well. You could also implement some sort of "or" statement somewhere to handle if a country doesn't have a GDP to change the message output. In terms of changing the color for your graph, I looked at different sources but also couldn't find a solution to change the colors. Though it may not be as nice stylistically, you could always have your graph in a div or some other container and keep the background color white, while changing the entire page's background to match your dark theme. Overall it looks great!

**Comment by datdinh7719** [comment]
Hi,
Your code look really good. I really like the background that you have for the home page and the dark background in list. I also like that the flags in each card stay the same size regardless of the viewport size. With my implementation, the size of the card changes so the flag can sometime be cutoff. I just notice i feel minor thing such as large number missing the comma such as "2331" on the list page. On the population chart, some of the countries' population is so small that it is hard to hover over to get more information. For your navbar, I feel like the first and last element is a bit too close to the edge and could use some padding. When clicking on an element of the nav bar, it becomes highlighted and stay highlighted after we arrive at the next page. I think that having that element remain active could be helpful to let the user knows what page they are on. But the link stop being highlighted once you click anywhere else. I think it should remain highlighted or not be highlighted at all after we click on it and move the cursor away so it's not hover over the link anymore.
Great work!

**Comment by turrilld** [comment]
Updated the nav bar to use <NavLink> instead of <Link> which has better support for active site handling.  Updated the hover and active page colors for the navbar.  Added missing data handling for list, added alt text for flags back in.  Attempted to add logarithmic scaling for my bar charts so that small numbers are not lost.

**Pull request merged**
